--- # Loop Playbook
- hosts: slave
  user: ansible
  sudo: yes
  connection: ssh
  gather_facts: no
  tasks:
   - name: add a list of users
     user: name={{ item}} state=present
     with_items:
       - user1
       - user2
       - user3
...
