--- # My First YAML playbooks
- hosts: slave
  user: ansible
  sudo: yes
  connection: ssh
  gather_facts: no
  tasks:
    - name: Install HTTPD server on RHEL 7
      action: yum name=httpd state=installed
...
